### ISSUE TITLE
filterKey is not required but required :)

### ISSUE THREAD

**Issue by boskiv** [unlock-protocol/unlock#12345]
in `https://github.com/unlock-protocol/unlock/blob/master/packages/unlock-js/openapi.yml#L1267`
```
- in: query
          name: filterKey
          required: false
          schema:
            type: string
```
But query to `https://locksmith.unlock-protocol.com/v2/api/137/locks/0x622e617fe917d040714dab2816410ed7cfbad8e1/keys`
Response with:
```
{"message":"No filterKey query found."}
```
